development:
  adapter: mysql2
  database: curriculum_development
  pool: 5
  reconnect: false
  encoding: utf8
  username: root
  password: bootcamp

test:
  adapter: mysql2
  database: curriculum_test
  pool: 5
  reconnect: false
  encoding: utf8
  username: root
  password: bootcamp

