development:
  adapter: sqlite3
  database: db/curriculum_development
  pool: 5
  reconnect: false
  encoding: utf8
  #username: root
  #password: bootcamp

test:
  adapter: sqlite3
  database: db/curriculum_test
  pool: 5
  reconnect: false
  encoding: utf8
  #username: root
  #password: bootcamp

