development:
  adapter: sqlite3
  database: db/curriculum_development.sqlite3
  pool: 5
  reconnect: false
  encoding: utf8
  #username: root
  #password: bootcamp

test:
  adapter: sqlite3
  database: db/curriculum_test.sqlite3
  pool: 5
  reconnect: false
  encoding: utf8
  #username: root
  #password: bootcamp

