require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EssaysController do

  # This should return the minimal set of attributes required to create a valid
  # Essay. As you add validations to Essay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "question" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EssaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all essays as @essays" do
      essay = Essay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:essays).should eq([essay])
    end
  end

  describe "GET show" do
    it "assigns the requested essay as @essay" do
      essay = Essay.create! valid_attributes
      get :show, {:id => essay.to_param}, valid_session
      assigns(:essay).should eq(essay)
    end
  end

  describe "GET new" do
    it "assigns a new essay as @essay" do
      get :new, {}, valid_session
      assigns(:essay).should be_a_new(Essay)
    end
  end

  describe "GET edit" do
    it "assigns the requested essay as @essay" do
      essay = Essay.create! valid_attributes
      get :edit, {:id => essay.to_param}, valid_session
      assigns(:essay).should eq(essay)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Essay" do
        expect {
          post :create, {:essay => valid_attributes}, valid_session
        }.to change(Essay, :count).by(1)
      end

      it "assigns a newly created essay as @essay" do
        post :create, {:essay => valid_attributes}, valid_session
        assigns(:essay).should be_a(Essay)
        assigns(:essay).should be_persisted
      end

      it "redirects to the created essay" do
        post :create, {:essay => valid_attributes}, valid_session
        response.should redirect_to(Essay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved essay as @essay" do
        # Trigger the behavior that occurs when invalid params are submitted
        Essay.any_instance.stub(:save).and_return(false)
        post :create, {:essay => { "question" => "invalid value" }}, valid_session
        assigns(:essay).should be_a_new(Essay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Essay.any_instance.stub(:save).and_return(false)
        post :create, {:essay => { "question" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested essay" do
        essay = Essay.create! valid_attributes
        # Assuming there are no other essays in the database, this
        # specifies that the Essay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Essay.any_instance.should_receive(:update_attributes).with({ "question" => "MyString" })
        put :update, {:id => essay.to_param, :essay => { "question" => "MyString" }}, valid_session
      end

      it "assigns the requested essay as @essay" do
        essay = Essay.create! valid_attributes
        put :update, {:id => essay.to_param, :essay => valid_attributes}, valid_session
        assigns(:essay).should eq(essay)
      end

      it "redirects to the essay" do
        essay = Essay.create! valid_attributes
        put :update, {:id => essay.to_param, :essay => valid_attributes}, valid_session
        response.should redirect_to(essay)
      end
    end

    describe "with invalid params" do
      it "assigns the essay as @essay" do
        essay = Essay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Essay.any_instance.stub(:save).and_return(false)
        put :update, {:id => essay.to_param, :essay => { "question" => "invalid value" }}, valid_session
        assigns(:essay).should eq(essay)
      end

      it "re-renders the 'edit' template" do
        essay = Essay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Essay.any_instance.stub(:save).and_return(false)
        put :update, {:id => essay.to_param, :essay => { "question" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested essay" do
      essay = Essay.create! valid_attributes
      expect {
        delete :destroy, {:id => essay.to_param}, valid_session
      }.to change(Essay, :count).by(-1)
    end

    it "redirects to the essays list" do
      essay = Essay.create! valid_attributes
      delete :destroy, {:id => essay.to_param}, valid_session
      response.should redirect_to(essays_url)
    end
  end

end
